version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_USER: user
      MYSQL_ROOT_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/nexpro-vonage-sample/
    ports:
      - 3000:3000
    depends_on:
      - db

  phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
          PMA_ARBITRARY: 1
          PMA_HOSTS: db
          PMA_USER: root
          PMA_PASSWORD: pass
        ports:
            - "8080:80"
        depends_on:
            - db

volumes:
  mysql_data: